# One file per Grafana account, generated by bin/sync.sh from grafana_orgs
# in config.yaml — do not edit or copy by hand; the sync rewrites these
# files and page.tf's lists on every run. Provider configurations
# cannot be created dynamically, so a per-org root file is the ceiling of
# what OpenTofu allows; everything about an org — its checks, its budget,
# its credentials — follows from its key in config.yaml.

provider "grafana" {
  alias                     = "example_cloud"
  cloud_access_policy_token = var.grafana_cloud_tokens["example"]
}

# The sm credentials come out of this file's installation resource — one
# apply hands the credential from one control plane to the other, which is
# the reason this stack is OpenTofu in the first place.
provider "grafana" {
  alias           = "example_sm"
  sm_access_token = grafana_synthetic_monitoring_installation.example.sm_access_token
  sm_url          = grafana_synthetic_monitoring_installation.example.stack_sm_api_url
}

data "grafana_cloud_stack" "example" {
  provider = grafana.example_cloud
  slug     = local.config.grafana_orgs["example"].stack_slug
}

# Synthetic Monitoring installation: the bootstrap that turns a stack into
# something probes can publish to. Lives here because the sm provider is
# configured from its outputs.
resource "grafana_cloud_access_policy" "example_sm_publish" {
  provider = grafana.example_cloud

  region       = data.grafana_cloud_stack.example.region_slug
  name         = "${local.config.grafana_orgs["example"].stack_slug}-sm-publish"
  display_name = "Synthetic Monitoring publisher (${local.config.grafana_orgs["example"].stack_slug})"
  scopes       = ["metrics:write", "stacks:read", "logs:write", "traces:write"]

  realm {
    type       = "stack"
    identifier = data.grafana_cloud_stack.example.id
  }
}

resource "grafana_cloud_access_policy_token" "example_sm_publish" {
  provider = grafana.example_cloud

  region           = data.grafana_cloud_stack.example.region_slug
  access_policy_id = grafana_cloud_access_policy.example_sm_publish.policy_id
  name             = "${local.config.grafana_orgs["example"].stack_slug}-sm-publish"
}

resource "grafana_synthetic_monitoring_installation" "example" {
  provider = grafana.example_cloud

  stack_id              = data.grafana_cloud_stack.example.id
  metrics_publisher_key = grafana_cloud_access_policy_token.example_sm_publish.token
}

# The ref is stamped from the release you cloned; see docs/setup-guide.md.
module "checks_example" {
  source = "github.com/lexbrugman/serverless-status//modules/checks?ref=master"

  providers = {
    grafana.cloud = grafana.example_cloud
    grafana.sm    = grafana.example_sm
  }

  stack_slug               = local.config.grafana_orgs["example"].stack_slug
  checks                   = module.routing.org_checks["example"]
  monthly_execution_budget = local.config.grafana_orgs["example"].monthly_execution_budget

  sm_api_url      = grafana_synthetic_monitoring_installation.example.stack_sm_api_url
  sm_access_token = grafana_synthetic_monitoring_installation.example.sm_access_token

  depends_on = [grafana_synthetic_monitoring_installation.example]
}

# Configured from what the checks module minted, so the stack's own API is
# reachable without a second credential in GitHub.
provider "grafana" {
  alias = "example_stack"
  url   = module.checks_example.stack.url
  auth  = module.checks_example.stack.auth
}

# The ref is stamped from the release you cloned; see docs/setup-guide.md.
module "alerting_example" {
  source = "github.com/lexbrugman/serverless-status//modules/alerting?ref=master"
  # Created whenever there is anything to watch at all: a check that opted
  # out of down-alerting is still one nobody wants silently unmonitored.
  count = length(local.alerting.email_addresses) > 0 && length(module.checks_example.check_manifest.checks) > 0 ? 1 : 0

  providers = {
    grafana.stack = grafana.example_stack
  }

  # Frequencies come from the resolved manifest, not from the config file:
  # a check that states none still runs at its type's default, and the
  # window a verdict is made over is a multiple of whatever it actually is.
  down_jobs = [
    for key, check in module.checks_example.check_manifest.checks :
    { key = key, frequency_minutes = check.frequency_minutes }
    if contains(module.routing.org_alert_jobs["example"], key)
  ]
  reporting_jobs = [
    for key, check in module.checks_example.check_manifest.checks :
    {
      key               = key
      display           = check.display
      target            = check.target
      frequency_minutes = check.frequency_minutes
    }
  ]
  page_url             = "https://${local.config.domain}"
  prometheus           = module.checks_example.prometheus
  email_addresses      = local.alerting.email_addresses
  down_window_multiple = local.page.down_window_multiple
  down_quorum          = local.page.down_quorum
}

# What this account's checks will spend in a 30-day month, from their
# frequencies and probe locations — the same number the budget precondition
# enforces, surfaced so it can be read without provoking a failure.
output "monthly_executions_example" {
  description = "Projected Synthetic Monitoring executions per month for the example account."
  value       = module.checks_example.monthly_executions
}

# The other allowance these checks spend. Executions are projected from the
# configuration; series can only be read, because what each check publishes
# is Grafana's to decide.
output "metrics_series_example" {
  description = "Metrics series in use for the example account, against the ceiling Grafana enforces — which sits above the allowance the subscription includes, so watch the smaller figure the Cloud Portal shows."
  value       = module.checks_example.metrics_series
}
